### ISSUE TITLE
How to use with espeak?

### ISSUE THREAD

**Issue by tete-github** [CMB/edbrowse#101]
Hello, I heard edbrowse was written by a blind person,
how do they use it? With a screenreader, speakup ... or how?

I think it should be something with tee and pipe, as I would like
to see and hear the output.

**Comment by eklhad** [comment]
I (author) use it with my own speech adapter, which I also wrote, which 
nobody else in the world uses, 
but, 
lots of people use it with lots of different screen readers and 
adapters, and I'm sure they can comment. 
The cool thing is, it's just an application, and thus largely 
orthogonal to your adaptive technology.

Karl Dahlke

**Comment by David-Apps** [comment]
In a command-line interface, blind people typically use screen reader software to speak (or send to their braille display) both the commands that they type and the output that their commands print to the screen.
They usually want to get the output of the keys that they press as they type them.
This is just like sighted people wanting the screen to show both the commands that they type (as they type them) and the output of those commands.
Screen reader software usually gives some way to review the previous output.
This is like sighted people wanting to look at the output of previous commands on their screen.
This is why blind people usually want to use screen reader software or speech adapter software instead of piping commands to a speech synthesizer.
I hope that this simplified explanation helps.

Edbrowse works very well with all the screen reader software that I have used it with.

If you are using a non-graphical terminal in a Debian-based distribution, you can often get the Speakup screen reader speaking with eSpeak NG by installing the espeakup package.

If you are using a graphical desktop environment in a GNU/Linux distribution, you could try the Orca screen reader.

If you are using the Windows Subsystem for Linux on Microsoft Windows, you could use the Microsoft Narrator or NVDA screen readers.
NVDA can use eSpeak NG.

I suggest that you try things in this order:

1. Start your screen reader software.
2. Make sure that your screen reader software reads your terminal to you.
3. Start edbrowse.

**Comment by tete-github** [comment]
Thank you for your replies.
