### ISSUE TITLE
Cannot get edbrowse to show more than around 40 utf-8 characters in a line (browser mode)

### ISSUE THREAD

**Issue by justa9** [CMB/edbrowse#46]
Hello.

At the moment I am unable to get edbrowse (3.7.4, static binary) show more than around 40 utf-8 characters in a line when browsing a non-english webpage. The result is a pretty narrow display of webpages which can make reading (for non-visually impaired people) a bit cumbersome. Setting "linelength" does not appear to have any kind of impact on this.

Any idea as to how can this situation be mitigated?

Thank you.

**Comment by eklhad** [comment]
Thank you. It took a while for me to track this down.
It isn't characters in a file, as I first thought, it is the formatted web page.
The function breakLine() in format.c cuts text into lines.
It is used by the bl command, and when formatting html.
It increments colno (column number) for every char, which is wrong, it should increment for every screen character, which is one ascii char or one utf8 character.
The fix is one line of code, fortunately, but does not help you running a static.
See my latest push.

Those wanting to replicate or verify...
See this test file I made.

eklhad.net/grin.html

It has a line of 120 grins.
Use the bl command on that line, or just browse the file.
Lines are very short, with so many grins, but after this push, lines are 80 chars as they should be.

Sorry I (English speaker) didn't see this coming.

Karl Dahlke

**Comment by justa9** [comment]
Thank you very much for the prompt and informative answer. 

If I am not mistaken, this fixes the situation with the narrow formatted page while still keeping the length of each line at around 80 screen characters. If this is the case, may I ask if a user-adjusted line length limit on the formatted webpage could be implemented ? That is, instead of the standard 80 characters line, the user could set a length of 120 characters or more should the terminal supports it.

Thank you again.

**Comment by martinetd** [comment]
Ideally we could try to probe the terminal with `TIOCGWINSZ` and look at ws_col to automatically get the maximum length we should use, but sometimes even with a large terminal I think it is better to truncate so I don't think it's necessarily a good idea to blindly probe.

Also when trying on the grin.html page, with the new patch I get 60 simleys per line, but these are wide characters so it actually accounts for 120 columns on my terminal.
Deciding which utf8 char is wide or not is a royal pain and I don't think we want to go there, so leaving it as a setting might make most sense...

**Comment by eklhad** [comment]
> a user-adjusted line length limit on the formatted webpage

I like this idea at many levels.
Perhaps

ll =

For line lengths in the editor before truncation, as we have today, and

fll =

formatted line length

The linelength = in the config file I don't need and almost wish I hadn't done,
cause you can always set ll = in the init() function.
And similarly you could set fll = in init() if you want a default other than 80.

Karl Dahlke

**Comment by justa9** [comment]
I think that "fll" could save the day, so to speak, and I am looking forward to seeing it implemented in a future release of edbrowse.

I would like to thank you again for your time and the informative answers.

**Comment by eklhad** [comment]
> I think that "fll" could save the day,

It is there, tested, documented, but only if you build the latest from github, which a lot of people don't cause it's not trivial, and I get that.
As per statics we kinda build them on each release or when the mood strikes us.

Karl Dahlke
