### ISSUE TITLE
[Enhancement] Ability to print URL of the current page

### ISSUE THREAD

**Issue by justa9** [CMB/edbrowse#48]
If I'm not mistaken, there isn't an immediate way to get the URL of the current session.

One can either use the "f" command or search through the sessions returned by "bflist", in order to derive the URL (i.e. remove the ".browse" part). However both of these ways fail to return the URL, if the user has altered the name of the session (for example, via the "f/" command). 

I am not sure whether the URL is stored internally after the initial fetch, so I was wondering whether an implementation of a function (just like "ft", or "fd") that returns it seems feasible.

Thank you.

**Comment by eklhad** [comment]
There are a couple things to consider here.

First, I don't know why you would change the name of a browsed file.
But let's say you wanted to, maybe to save the browsed text somewhere.
The f/ command doesn't work well  in some browsing situations,
like https://www.nasa.gov/
so maybe I need to work on that.
Some people use the A command on a line that doesn't have a link, like

/^$/A

and the first line has the url without the .browse, and a few substitutes can get rid of the tags around it,
but it is url encoded, as it should be for this context,
and that's probably not what you want.
And besides this also changes if you change the file name.

The original url is preserved in cf->hbase.
It is the base for any future href= directives and it doesn't change with the file name.
In theory one could just print it out.
You mentioned the f commands, I could imagine fu for file url,
imagine the joy of typing fu into edbrowse.
Reminds me of the Odd Couple movie,
"It took me 15 minutes to realize that FU meant Felix Ungar!"

But this leads to another question.

cf is my global variable for current frame, cw is current window.
A window can present many frames.
Would you always want the url of the window, that is, the top frame,
or perhaps the frame you are currently looking at?
The A command always goes by the window, since you are bookmarking the entire window.
I suppose you would want the url of the window, even if you were looking inside a particular frame.

Karl Dahlke

**Comment by eklhad** [comment]
I'm following up with a little more ambiguity.

Suppose you typed in www.eklhad.net/foo bar
This is converted before it gets to base.
Since there is no protocol, http: is added, and I don't think you'd have a problem with that.
The url would start with http:// where it didn't before.
But, it is also encoded for you, so space becomes %20, like this.

http://www.eklhad.net/foo%20bar

That's not the way you typed it in, and it looks strange,
especially if you're a casual user who doesn't no the details or url encodings and the internet.
Well then, you might say, keep a copy of what was typed in before it gets cleaned up, and show that, but,
suppose you got to this page by clicking on a link from another page.
Then it will indeed be encoded from the get-go.
Same web page but fu has to show the encoded url, because that's what it started with.

I know, you asked such a simple question, and it sort of opens a can of worms,
but that's the internet for  you.

Karl Dahlke

**Comment by justa9** [comment]
On the contrary, thank you very much for the detailed information. It presents things that I hadn't thought about.

I would suggest that "fu" returns the URL that is sent to the remote server. This would include encoded spaces, symbols or non-ASCII letters, and would correspond to the URL of the window (if no redirections occur).

**Comment by eklhad** [comment]
Ok see latest commit.
It was only 6 lines of code, more than that just to document.  :)
Also fixed a couple bugs along the way.
Like the A command that would change if you changed the file name, and that one really shouldn't.

fu prints the url, but if you want to capture it for some reason you can do this in a script.

/^$/A
2,3d
s/^<a href=//
s/>$//
bw

Then you can do something with it and ^ back to the page you were on.

Karl Dahlke

**Comment by justa9** [comment]
Thank you very much.
