### ISSUE TITLE
Can't log in to google - says JavaScript is not supported

### ISSUE THREAD

**Issue by OParczyk** [CMB/edbrowse#60]
Hi again! Today I tried logging into my Google account using edbrowse (w/ activated JS of course) and it went like this:

> $ LC_ALL=C edbrowse
> Edbrowse bereit
> e https://google.com/ncr
> 12579
> b
> 352
> ,n
> 1 Search {Images} {Maps} {Play} {YouTube} {Gmail} {Drive} {Calendar} {More »}
> 2 {Web History} | {Settings} | {Sign in}
> 3 
> 4 [Google]
> 5 
> 6 <>
> 7 <Google Search (gesichert)><I'm Feeling Lucky (gesichert)> {Advanced
> 8 search}{Language tools}
> 9 
> 10 Google offered in: {Deutsch}
> 11 {Advertising Programs}{Business Solutions}{About Google}{Google.de}
> 12 
> 13 © 2019 - {Privacy} - {Terms}
> 2g3
> 73237
> 325
> ,n
> 1 h1 One account. All of Google.
> 2 
> 3 h2 Sign in with your Google Account
> 4 
> 5 Enter your email <> <>
> 6 <Next (gesichert)> {Find my account}
> 7 
> 8 {Sign in with a different account} {Create account}
> 9 
> 10 One Google Account for everything Google
> 11 
> 12 * {About Google}
> 13 * {Privacy}
> 14 * {Terms}
> 15 * {Help}
> 16 
> 17 [Change language] <‪English (United States)‬>
> 18 
> 5i1=me@googlemail.com
> Enter your email <me@googlemail.com> <>
> 6i*
> Formularfeld(er) versandt
> 72640
> 516
> ,n
> 1 h1 One account. All of Google.
> 2 
> 3 h2 Sign in with your Google Account
> 4 
> 5 {Back}
> 6 
> 7 me@googlemail.com
> 8 <me@googlemail.com> Password <>
> 9 <Sign in (gesichert)> <+> Stay signed in
> 10 For your convenience, keep this checked.
> 11 On shared devices, additional precautions are recommended. {Learn more}
> 12 {Forgot password?}
> 13 
> 14 {Sign in with a different account} {Create account}
> 15 
> 16 One Google Account for everything Google
> 17 
> 18 * {About Google}
> 19 * {Privacy}
> 20 * {Terms}
> 21 * {Help}
> 22 
> 23 [Change language] <‪English (United States)‬>
> 24 
> 8i2=mypass
> <me@googlemail.com> Password <****************************************************************>
> 9i*
> Formularfeld(er) versandt
> 18621
> 299
> ,n
> 1 h1 Couldn't sign you in
> 2 
> 3 The browser you're using doesn't support JavaScript,
> 4 or has JavaScript turned off.
> 5 
> 6 To keep your Google Account secure, try signing in on a browser that has
> 7 JavaScript turned on. {Learn more}
> 8 
> 9 * Google
> 10 * {Privacy}
> 11 * {Terms}
> 12 
> 13 [Change language]<‪English (United States)‬>

Sorry for the wall of text, I deemed I shouldn't crop it, changed username and password though.

Did I do something very wrong?

Thanks for your Time,
Oliver

**Comment by eklhad** [comment]
The really annoying thing about google is, it's vitally important, and, it keeps changing all the time.

Example, just a few weeks ago the search function, which is what I do 99% of the time, lost its h3 headers, and became almost unreadable, almost unusable!
I need to look at the generated html and see if I can muck with it, in an edbrowse function, in some fashion, to put the headers back again so the search results are clearly marked.
Pain in the ass!

Now on to your question.

I have for years logged into google, with javascript turned off of course, but not very often, because hardly ever do I have to log into that thing.
I accessed gmail by web for a while, and that was pretty awkward, but manageable, but that gave me the insentive to get imap working,
and now I fetch my gmail by pop3 95% of the time, and once in a while go in by imap to check my spam folder and empty the trash, and boom that takes care of everything gmail.

Now let's say I still need to log in once a year for some reason.
I could do it before, but I can't now.
Exactly as you wrote (though of course the english version).
Something has changed.
For grins I took out the nojs google.com line and let it run with javascript.
I logged in just fine.
Even accessed my gmail through the web interface.
Deleted a couple of emails from the spam folder.
Then signed out.
It all worked; I'm kinda surprised.
But, you have to put nojs google.com back in before you do a search.
Something about google search and javascript puts you in an infinite loop.
The page just refreshes and refreshes and refreshes.
If someone wanted to debug that, then maybe we could leave js on all the time.

Karl Dahlke

**Comment by OParczyk** [comment]
Removing the `nojs`-line and making disabling JS before a Google-search a habit resolves this issue. As there is another one open for the endless reload, I consider this one solved.

Thank you!
