### ISSUE TITLE
pcre -> pcre2

### ISSUE THREAD

**Issue by sthibaul** [CMB/edbrowse#76]
As reported in Debian https://bugs.debian.org/1000056 , pcre has been end-of-life for a while now, upstream won't
fix it any more, and people are invited to migrate to pcre2 (available since 2015)

We will need edbrowse to be migrated to pcre2 before the next Debian release freeze circa end of 2022.

Upstream's documentation is available on
https://pcre.org/current/doc/html/

**Comment by eklhad** [comment]
> migrate to pcre2 (available since 2015)

This has already been done:
1d9a2e966ddb5242d79e4b6e238124c4be81f6dd

If you are suggesting we release version 3.8.1, with this and other important changes in it, I agree.
Sometimes you just have to put a label on it, even though issues remain, because issues will always remain.
Hopefully we can release 3.8.1 this year.

Karl Dahlke

**Comment by sthibaul** [comment]
> migrate to pcre2 (available since 2015)
> This has already been done: [1d9a2e9](https://github.com/CMB/edbrowse/commit/1d9a2e966ddb5242d79e4b6e238124c4be81f6dd)

Oh, thanks!
